Feature/add env for container
erda-project/flink-on-k8s-operator pull request #1
Opened 2021-08-27 14:06 UTC by chengjoey

add env for container and change dockerfile kubebuilder installation

2021-08-27 14:15 UTC, sfwn requested changes

2021-08-27 14:15 UTC, sfwn commented on Dockerfile.builder
> +FROM amd64/ubuntu:18.04
Can I build this image on my non-amd machine?

2021-08-27 14:29 UTC, chengjoey commented on Dockerfile.builder
> +FROM amd64/ubuntu:18.04
yeah,i build this image in my arm machine. specifies amd64 because it will pull arm ubuntu image if local machine is arm

2021-08-27 14:36 UTC, sfwn submitted a review, later dismissed

2021-08-27 14:37 UTC, sfwn commented
/approve

2021-08-28 01:52 UTC, sfwn approved these changes, later dismissed

2021-08-28 02:35 UTC, closed without merging